config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'

  resources :products do
    resources :reserves do
      get 'confirmation'
    end
  collection do
    get 'about'
    get 'contact'
    post 'contact'
  end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/facility.rb
class Facility < ApplicationRecord
  has_many :product_facilities
  has_many :products, through: :product_facilities
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :product_features
  has_many :products, through: :product_features
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :room
  belongs_to :reservation
  has_many :images
  has_many :product_categories
  has_many :product_facilities
  has_many :product_features
  has_many :categories, through: :product_categories
  has_many :facilities, through: :product_facilities
  has_many :features,   through: :product_features
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_facility.rb
class ProductFacility < ApplicationRecord
  belongs_to :product
  belongs_to :facility
end

app/models/product_feature.rb
class ProductFeature < ApplicationRecord
  belongs_to :product
  belongs_to :feature
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  has_one    :product
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def reserve
  end

  def about
  end

  def contact
    @contact = Contact.new
  end
  
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController

  def index
    @product = Product.find(params[:product_id])
  end

  def new
    @product = Product.find(params[:product_id])
  end

  def create
  end

  def confirmation
    @product = Product.find(params[:product_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CampReservation
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css", rel: "stylesheet", type: "text/css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
  %body
    = render 'modules/header'
    = yield
    = render 'modules/footer'

app/views/modules/_footer.html.haml
.footer
  .footer__inner
    camp_reservation

app/views/modules/_header.html.haml
.header
  .header__heading
    = link_to root_path do
      キャンプ予約システム

app/views/modules/_information.html.haml
.information
  .information__contents
    %ul.information__contents__list
      %li.about_us
        = link_to about_products_path do
          About Us
      %li.contact
        = link_to contact_products_path do
          お問い合わせ

app/views/products/_products.html.haml
.products
  - products.each do |product|
    .products__content
      .products__content__image
        = image_tag "/images/a.jpg"
      .products__content__detail
        %p.detail-name
          = product.room.name
        %p.detail-category
          - product.categories.each do |category|
            %span
              = category.name
        %p.detail-price
          %span
            = product.room.workday_price.to_s(:delimited).insert(0, "¥ ").insert(-1, "～")
          %span
            （1室1泊料金）
        %p.reserve-btn
          = link_to product_path(product) do
            予約する
      %p.detail
        = link_to "", class: '' do
          詳細情報

app/views/products/_search.html.haml
.search
  %ul.search__date
    %li.checkin
      %p チェックイン
      %p
        %input{type: "text", placeholder: "年／月／日"}
    %li.checkout
      %p チェックアウト
      %p
        %input{type: "text", placeholder: "年／月／日"}
    %li.checkbox
      %label
        .check-area
          %input{type: "checkbox", checked: "checked"}
          日付未定
  %ul.search__num
    %li.room
      %p 客室数
      %select
        %option{selected: "selected", value: "1"} 1
        %option{value: "2"} 2
        %option{value: "3"} 3
        %option{value: "4"} 4
    %li.person
      %ul
        %li
          %p.age 大人
          %p.room
            %a
              %span 8
              名
        %li
          %p.age 子供
          %p.room
            %a
              %span 8
              名
  .search__btn
    %input{type: "submit", value: "検索する"}

app/views/products/_slick.html.haml
.slick
  .slick__content
    = image_tag "/images/a.jpg", class: 'slick__content--img'
  .slick__content
    = image_tag "/images/b.jpg", class: 'slick__content--img'
  .slick__content
    = image_tag "/images/c.jpg", class: 'slick__content--img'
  .slick__content
    = image_tag "/images/d.jpg", class: 'slick__content--img'
  .slick__content
    = image_tag "/images/e.jpg", class: 'slick__content--img'

app/views/products/about.html.haml
.products-about
  .products-about__heading
    = render 'modules/information'
  .products-about__description
    %p
      xxxキャンプ場
    %p
      xxxタイプで作成しました。
  .products-about__info
    .products-about__info__item
      %p
        お問い合わせ電話番号
      %span 03-1234-5678
    .products-about__info__item
      %p
        URL
      %span
        = link_to root_path do
          https://camp_reservation
    .products-about__info__item
      %p
        所在地
      %span 東京都千代田区1-2-3
  .products-about__map

app/views/products/contact.html.haml
.products-contact
  .products-contact__heading
    %h3
      お問い合わせ
    = render 'modules/information'
  .products-contact__form
    .products-contact__form__heading
      お問い合わせ内容を入力してください
    = form_with(model: @tweet, local: true) do |form|
      .input-name
        氏名
        %span *
      = form.text_field :full_name, placeholder: "東京 太郎"
      .input-name
        メールアドレス
        %span *
      = form.text_field :email, placeholder: "メールアドレス"
      .input-name 電話番号
      = form.text_field :phone_number, placeholder: "000-1234-5678"
      .input-name
        タイトル
        %span *
      = form.text_field :title
      .input-name
        お問い合わせ内容
        %span *
      = form.text_area :detail, placeholder: "お問い合わせ内容をご入力ください", rows: "10"
      .input-btn
        = form.submit "お問い合わせを送信する"

app/views/products/index.html.haml
= render 'products/slick'
.products-index
  = render 'modules/information'
  = render 'products/search'
  = render partial: 'products', locals: { products: @products }

app/views/products/show.html.haml
.content
  .product_id
    部屋id：
    = @product.id
  .room_name
    部屋名：
    = @product.room.name
  .product_description
    部屋説明：
    = @product.description
  .product_features
    部屋特徴：
    - @product.features.each do |feature|
      = feature.name
  .product_facilities
    設備・アメニティ：
    - @product.facilities.each do |facility|
      = facility.name
  .product_categories
    - @product.categories.each do |category|
      = category.name
  = link_to product_reserves_path(@product) do
    予約する

app/views/reserves/confirmation.html.haml
.content
  予約完了画面
.complete
  = link_to '' do
    完了する

app/views/reserves/create.html.haml
.content
  予約が完了しました。

app/views/reserves/index.html.haml
.content
  予約画面
.reserve
  = link_to new_product_reserf_path(@product) do
    予約する

app/views/reserves/new.html.haml
.content
  予約入力フォーム
.confirmation
  = link_to product_reserf_confirmation_path(@product, 1) do
    確認する